// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Traxon.CryptoTrader.Infrastructure.Persistence;

#nullable disable

namespace Traxon.CryptoTrader.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Traxon.CryptoTrader.Domain.Market.Candle", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,8)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("QuoteVolume")
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("TradeCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("OpenTime")
                        .HasDatabaseName("IX_Candles_OpenTime");

                    b.ToTable("Candles", (string)null);
                });

            modelBuilder.Entity("Traxon.CryptoTrader.Domain.Trading.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Edge")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("EntryReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("FairValue")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("IndicatorSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("KellyFraction")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("MuEstimate")
                        .HasColumnType("decimal(18,12)");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Outcome")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("PnL")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PositionSize")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SigmaEstimate")
                        .HasColumnType("decimal(18,12)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Engine", "OpenedAt")
                        .HasDatabaseName("IX_Trades_Engine_OpenedAt");

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("Traxon.CryptoTrader.Infrastructure.Persistence.Models.PortfolioSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OpenPositionCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalExposure")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalPnL")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TradeCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("WinRate")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Engine", "Timestamp")
                        .HasDatabaseName("IX_PortfolioSnapshots_Engine_Timestamp");

                    b.ToTable("PortfolioSnapshots", (string)null);
                });

            modelBuilder.Entity("Traxon.CryptoTrader.Domain.Market.Candle", b =>
                {
                    b.OwnsOne("Traxon.CryptoTrader.Domain.Assets.Asset", "Asset", b1 =>
                        {
                            b1.Property<long>("CandleId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Symbol");

                            b1.HasKey("CandleId");

                            b1.ToTable("Candles");

                            b1.WithOwner()
                                .HasForeignKey("CandleId");
                        });

                    b.OwnsOne("Traxon.CryptoTrader.Domain.Assets.TimeFrame", "TimeFrame", b1 =>
                        {
                            b1.Property<long>("CandleId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("Interval");

                            b1.HasKey("CandleId");

                            b1.ToTable("Candles");

                            b1.WithOwner()
                                .HasForeignKey("CandleId");
                        });

                    b.Navigation("Asset")
                        .IsRequired();

                    b.Navigation("TimeFrame")
                        .IsRequired();
                });

            modelBuilder.Entity("Traxon.CryptoTrader.Domain.Trading.Trade", b =>
                {
                    b.OwnsOne("Traxon.CryptoTrader.Domain.Assets.Asset", "Asset", b1 =>
                        {
                            b1.Property<Guid>("TradeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Symbol");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.OwnsOne("Traxon.CryptoTrader.Domain.Assets.TimeFrame", "TimeFrame", b1 =>
                        {
                            b1.Property<Guid>("TradeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("TimeFrame");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.Navigation("Asset")
                        .IsRequired();

                    b.Navigation("TimeFrame")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
